openapi: 3.0.2
info:
  title: HostServiceApi
  version: "1.0"
servers:
- url: /
paths:
  /authenticate:
    post:
      operationId: authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticateRequestContent"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticateResponseContent"
          description: Authenticate 200 response
      x-openapi-router-controller: internal_api_client.controllers.default_controller
  /internal/deprovision:
    post:
      operationId: deprovision_device
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeprovisionDeviceRequestContent"
      responses:
        "200":
          description: DeprovisionDevice 200 response
      x-openapi-router-controller: internal_api_client.controllers.default_controller
  /internal/host-config:
    get:
      operationId: get_host_config
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetHostConfigResponseContent"
          description: GetHostConfig 200 response
      x-openapi-router-controller: internal_api_client.controllers.default_controller
  /internal/log:
    post:
      operationId: request_log
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestLogRequestContent"
      responses:
        "200":
          description: RequestLog 200 response
      x-openapi-router-controller: internal_api_client.controllers.default_controller
  /internal/rotate-certs:
    post:
      operationId: rotate_certificates
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RotateCertificatesRequestContent"
        required: true
      responses:
        "200":
          description: RotateCertificates 200 response
      x-openapi-router-controller: internal_api_client.controllers.default_controller
  /internal/thumbnail:
    post:
      operationId: request_thumbnail
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestThumbnailRequestContent"
        required: true
      responses:
        "200":
          description: RequestThumbnail 200 response
      x-openapi-router-controller: internal_api_client.controllers.default_controller
  /internal/version:
    get:
      operationId: get_version
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetVersionResponseContent"
          description: GetVersion 200 response
      x-openapi-router-controller: internal_api_client.controllers.default_controller
  /pair:
    post:
      operationId: pair
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PairRequestContent"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PairResponseContent"
          description: Pair 200 response
      x-openapi-router-controller: internal_api_client.controllers.default_controller
components:
  schemas:
    AuthStatus:
      enum:
      - STANDBY
      - CLAIMED
      title: AuthStatus
      type: string
    AuthenticateRequestContent:
      example:
        accessCode: accessCode
        deviceId: deviceId
        pairingCode: pairingCode
      properties:
        deviceId:
          title: deviceId
          type: string
        pairingCode:
          title: pairingCode
          type: string
        accessCode:
          title: accessCode
          type: string
      required:
      - accessCode
      - deviceId
      - pairingCode
      title: AuthenticateRequestContent
      type: object
    AuthenticateResponseContent:
      example:
        deviceCert: deviceCert
        caCert: caCert
        hostSettings:
          pairingTimeoutSeconds: 0.8008281904610115
          subUpdateTopic: subUpdateTopic
          pubReportStatusTopic: pubReportStatusTopic
          minIntervalPubSeconds: 6.027456183070403
          subUpdateCertsTopic: subUpdateCertsTopic
          pubReportRegistrationTopic: pubReportRegistrationTopic
          pubDeprovisionTopic: pubDeprovisionTopic
          subDeprovisionTopic: subDeprovisionTopic
          pubReportSchemaTopic: pubReportSchemaTopic
          subUpdateThumbnailSubscriptionTopic: subUpdateThumbnailSubscriptionTopic
          subUpdateLogSubscriptionTopic: subUpdateLogSubscriptionTopic
          iotProtocolName: iotProtocolName
          mqttKeepaliveSeconds: 1.4658129805029452
          pubReportActualConfigurationTopic: pubReportActualConfigurationTopic
        mqttUri: mqttUri
        region: region
        status: STANDBY
      properties:
        status:
          $ref: "#/components/schemas/AuthStatus"
        caCert:
          title: caCert
          type: string
        deviceCert:
          title: deviceCert
          type: string
        mqttUri:
          title: mqttUri
          type: string
        region:
          title: region
          type: string
        hostSettings:
          $ref: "#/components/schemas/HostSettings"
      required:
      - status
      title: AuthenticateResponseContent
      type: object
    DeprovisionDeviceRequestContent:
      example:
        reason: DEPROVISIONED
        time: 0.8008281904610115
      properties:
        reason:
          $ref: "#/components/schemas/DeprovisionReason"
        time:
          title: time
          type: number
      title: DeprovisionDeviceRequestContent
      type: object
    DeprovisionReason:
      enum:
      - DEPROVISIONED
      - EXPIRED
      - UNKNOWN
      title: DeprovisionReason
      type: string
    GetHostConfigResponseContent:
      example:
        authUrl: authUrl
        deviceTypes:
        - deviceTypes
        - deviceTypes
        thumbnailMaxSizeKB: 0.8008281904610115
        logFileMaxSizeKB: 6.027456183070403
        pairingUrl: pairingUrl
        serviceId: serviceId
        serviceName: serviceName
      properties:
        serviceId:
          title: serviceId
          type: string
        serviceName:
          title: serviceName
          type: string
        deviceTypes:
          items:
            type: string
          title: deviceTypes
          type: array
        thumbnailMaxSizeKB:
          title: thumbnailMaxSizeKB
          type: number
        logFileMaxSizeKB:
          title: logFileMaxSizeKB
          type: number
        pairingUrl:
          title: pairingUrl
          type: string
        authUrl:
          title: authUrl
          type: string
      required:
      - authUrl
      - deviceTypes
      - logFileMaxSizeKB
      - pairingUrl
      - serviceId
      - serviceName
      - thumbnailMaxSizeKB
      title: GetHostConfigResponseContent
      type: object
    GetVersionResponseContent:
      example:
        version:
          version: 1.0.0
      properties:
        version:
          $ref: "#/components/schemas/ProtocolVersion"
      required:
      - version
      title: GetVersionResponseContent
      type: object
    HostSettings:
      example:
        pairingTimeoutSeconds: 0.8008281904610115
        subUpdateTopic: subUpdateTopic
        pubReportStatusTopic: pubReportStatusTopic
        minIntervalPubSeconds: 6.027456183070403
        subUpdateCertsTopic: subUpdateCertsTopic
        pubReportRegistrationTopic: pubReportRegistrationTopic
        pubDeprovisionTopic: pubDeprovisionTopic
        subDeprovisionTopic: subDeprovisionTopic
        pubReportSchemaTopic: pubReportSchemaTopic
        subUpdateThumbnailSubscriptionTopic: subUpdateThumbnailSubscriptionTopic
        subUpdateLogSubscriptionTopic: subUpdateLogSubscriptionTopic
        iotProtocolName: iotProtocolName
        mqttKeepaliveSeconds: 1.4658129805029452
        pubReportActualConfigurationTopic: pubReportActualConfigurationTopic
      properties:
        iotProtocolName:
          title: iotProtocolName
          type: string
        pairingTimeoutSeconds:
          title: pairingTimeoutSeconds
          type: number
        minIntervalPubSeconds:
          title: minIntervalPubSeconds
          type: number
        mqttKeepaliveSeconds:
          title: mqttKeepaliveSeconds
          type: number
        subUpdateTopic:
          title: subUpdateTopic
          type: string
        subUpdateThumbnailSubscriptionTopic:
          title: subUpdateThumbnailSubscriptionTopic
          type: string
        pubReportSchemaTopic:
          title: pubReportSchemaTopic
          type: string
        pubReportRegistrationTopic:
          title: pubReportRegistrationTopic
          type: string
        pubReportStatusTopic:
          title: pubReportStatusTopic
          type: string
        pubReportActualConfigurationTopic:
          title: pubReportActualConfigurationTopic
          type: string
        subUpdateCertsTopic:
          title: subUpdateCertsTopic
          type: string
        pubDeprovisionTopic:
          title: pubDeprovisionTopic
          type: string
        subDeprovisionTopic:
          title: subDeprovisionTopic
          type: string
        subUpdateLogSubscriptionTopic:
          title: subUpdateLogSubscriptionTopic
          type: string
      required:
      - iotProtocolName
      - minIntervalPubSeconds
      - mqttKeepaliveSeconds
      - pairingTimeoutSeconds
      - pubDeprovisionTopic
      - pubReportActualConfigurationTopic
      - pubReportRegistrationTopic
      - pubReportSchemaTopic
      - pubReportStatusTopic
      - subDeprovisionTopic
      - subUpdateCertsTopic
      - subUpdateLogSubscriptionTopic
      - subUpdateThumbnailSubscriptionTopic
      - subUpdateTopic
      title: HostSettings
      type: object
    PairFailureData:
      properties:
        reason:
          $ref: "#/components/schemas/PairFailureReason"
      required:
      - reason
      title: PairFailureData
      type: object
    PairFailureReason:
      enum:
      - HOST_ID_MISMATCH
      - VERSION_NOT_SUPPORTED
      - DEVICE_TYPE_NOT_SUPPORTED
      title: PairFailureReason
      type: string
    PairRequestContent:
      example:
        deviceType: deviceType
        csr: csr
        hostId: hostId
        version: version
      properties:
        deviceType:
          title: deviceType
          type: string
        hostId:
          title: hostId
          type: string
        csr:
          title: csr
          type: string
        version:
          title: version
          type: string
      required:
      - csr
      - deviceType
      - hostId
      - version
      title: PairRequestContent
      type: object
    PairResponseContent:
      example:
        result:
          success:
            pairingTimeoutSeconds: 0.8008281904610115
            accessCode: accessCode
            deviceId: deviceId
            pairingCode: pairingCode
      properties:
        result:
          $ref: "#/components/schemas/PairResult"
      required:
      - result
      title: PairResponseContent
      type: object
    PairResult:
      oneOf:
      - $ref: "#/components/schemas/success"
      - $ref: "#/components/schemas/failure"
      title: PairResult
    PairSuccessData:
      example:
        pairingTimeoutSeconds: 0.8008281904610115
        accessCode: accessCode
        deviceId: deviceId
        pairingCode: pairingCode
      properties:
        deviceId:
          title: deviceId
          type: string
        pairingCode:
          title: pairingCode
          type: string
        accessCode:
          title: accessCode
          type: string
        pairingTimeoutSeconds:
          title: pairingTimeoutSeconds
          type: number
      required:
      - accessCode
      - deviceId
      - pairingCode
      - pairingTimeoutSeconds
      title: PairSuccessData
      type: object
    ProtocolVersion:
      example:
        version: 1.0.0
      properties:
        version:
          default: 1.0.0
          title: version
          type: string
      title: ProtocolVersion
      type: object
    RequestLogRequestContent:
      example:
        expires: 0.8008281904610115
        remotePath: remotePath
      properties:
        expires:
          title: expires
          type: number
        remotePath:
          title: remotePath
          type: string
      title: RequestLogRequestContent
      type: object
    RequestThumbnailRequestContent:
      example:
        requests:
          key:
            period: 0.8008281904610115
            expires: 6.027456183070403
            remotePath: remotePath
            localPath: localPath
            maxSizeKilobyte: 1.4658129805029452
      properties:
        requests:
          additionalProperties:
            $ref: "#/components/schemas/ThumbnailRequest"
          title: requests
          type: object
      required:
      - requests
      title: RequestThumbnailRequestContent
      type: object
    RotateCertificatesRequestContent:
      example:
        deviceCert: deviceCert
        mqttUri: mqttUri
        region: region
      properties:
        mqttUri:
          title: mqttUri
          type: string
        deviceCert:
          title: deviceCert
          type: string
        region:
          title: region
          type: string
      required:
      - deviceCert
      - mqttUri
      - region
      title: RotateCertificatesRequestContent
      type: object
    ThumbnailRequest:
      example:
        period: 0.8008281904610115
        expires: 6.027456183070403
        remotePath: remotePath
        localPath: localPath
        maxSizeKilobyte: 1.4658129805029452
      properties:
        period:
          title: period
          type: number
        expires:
          title: expires
          type: number
        maxSizeKilobyte:
          title: maxSizeKilobyte
          type: number
        localPath:
          title: localPath
          type: string
        remotePath:
          title: remotePath
          type: string
      title: ThumbnailRequest
      type: object
    ThumbnailRequestMap:
      additionalProperties:
        $ref: "#/components/schemas/ThumbnailRequest"
      title: requests
      type: object
    success:
      example:
        success:
          pairingTimeoutSeconds: 0.8008281904610115
          accessCode: accessCode
          deviceId: deviceId
          pairingCode: pairingCode
      properties:
        success:
          $ref: "#/components/schemas/PairSuccessData"
      required:
      - success
      title: success
      type: object
    failure:
      properties:
        failure:
          $ref: "#/components/schemas/PairFailureData"
      required:
      - failure
      title: failure
      type: object
