openapi: 3.0.2
info:
  title: CddService
  version: "1.0"
servers:
- url: /
paths:
  /connect:
    put:
      operationId: connect
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConnectRequestContent"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectResponseContent"
          description: Connect 200 response
      x-openapi-router-controller: openapi_client.controllers.default_controller
  /deprovision:
    put:
      operationId: deprovision
      parameters:
      - explode: true
        in: query
        name: host_id
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: force
        required: false
        schema:
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeprovisionResponseContent"
          description: Deprovision 200 response
      x-openapi-router-controller: openapi_client.controllers.default_controller
  /disconnect:
    put:
      operationId: disconnect
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DisconnectResponseContent"
          description: Disconnect 200 response
      x-openapi-router-controller: openapi_client.controllers.default_controller
  /get_configuration:
    get:
      operationId: get_configuration
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetConfigurationResponseContent"
          description: GetConfiguration 200 response
      x-openapi-router-controller: openapi_client.controllers.default_controller
  /get_state:
    get:
      operationId: get_connection_status
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetConnectionStatusResponseContent"
          description: GetConnectionStatus 200 response
      x-openapi-router-controller: openapi_client.controllers.default_controller
  /report_actual_configuration:
    put:
      operationId: report_actual_configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReportActualConfigurationRequestContent"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportActualConfigurationResponseContent"
          description: ReportActualConfiguration 200 response
      x-openapi-router-controller: openapi_client.controllers.default_controller
  /report_status:
    put:
      operationId: report_status
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReportStatusRequestContent"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReportStatusResponseContent"
          description: ReportStatus 200 response
      x-openapi-router-controller: openapi_client.controllers.default_controller
components:
  schemas:
    Channel:
      example:
        profileSetting:
        - name: name
          id: id
          info: info
        - name: name
          id: id
          info: info
        name: name
        channelType: SOURCE
        id: id
        simpleSettings:
        - enums:
            defaultValue: defaultValue
            values:
            - values
            - values
          ranges:
            min: 0.8008281904610115
            max: 6.027456183070403
            defaultValue: 1.4658129805029452
          name: name
          id: id
          info: info
        - enums:
            defaultValue: defaultValue
            values:
            - values
            - values
          ranges:
            min: 0.8008281904610115
            max: 6.027456183070403
            defaultValue: 1.4658129805029452
          name: name
          id: id
          info: info
        connectionProtocols:
        - SRT_LISTENER
        - SRT_LISTENER
      properties:
        name:
          title: name
          type: string
        id:
          title: id
          type: string
        channelType:
          $ref: "#/components/schemas/ChannelType"
        simpleSettings:
          items:
            $ref: "#/components/schemas/Setting"
          title: simpleSettings
          type: array
        profileSetting:
          items:
            $ref: "#/components/schemas/Profile"
          title: profileSetting
          type: array
        connectionProtocols:
          items:
            $ref: "#/components/schemas/SupportedProtocol"
          title: connectionProtocols
          type: array
      required:
      - id
      - name
      title: Channel
      type: object
    ChannelConfiguration:
      example:
        settings:
          simpleSettings:
          - value: value
            key: key
          - value: value
            key: key
        connection:
          transportProtocol:
            srtListener:
              streamId: streamId
              minimumLatencyMilliseconds: 6.027456183070403
              encryption:
                aes128:
                  passcode: passcode
              port: 6190.222739483032
              interface: interface
        id: id
        state: ACTIVE
      properties:
        id:
          title: id
          type: string
        state:
          $ref: "#/components/schemas/ChannelState"
        settings:
          $ref: "#/components/schemas/SettingsChoice"
        connection:
          $ref: "#/components/schemas/Connection"
      required:
      - id
      - state
      title: ChannelConfiguration
      type: object
    ChannelState:
      enum:
      - ACTIVE
      - IDLE
      title: ChannelState
      type: string
    ChannelStatus:
      example:
        id: id
        state: ACTIVE
        status:
        - name: name
          value: value
          info: info
        - name: name
          value: value
          info: info
      properties:
        id:
          title: id
          type: string
        state:
          $ref: "#/components/schemas/ChannelState"
        status:
          items:
            $ref: "#/components/schemas/StatusValue"
          title: status
          type: array
      required:
      - id
      - state
      - status
      title: ChannelStatus
      type: object
    ChannelType:
      enum:
      - SOURCE
      - DESTINATION
      title: ChannelType
      type: string
    ConfigurationData:
      example:
        updateId: updateId
        payload:
          channels:
          - settings:
              simpleSettings:
              - value: value
                key: key
              - value: value
                key: key
            connection:
              transportProtocol:
                srtListener:
                  streamId: streamId
                  minimumLatencyMilliseconds: 6.027456183070403
                  encryption:
                    aes128:
                      passcode: passcode
                  port: 6190.222739483032
                  interface: interface
            id: id
            state: ACTIVE
          - settings:
              simpleSettings:
              - value: value
                key: key
              - value: value
                key: key
            connection:
              transportProtocol:
                srtListener:
                  streamId: streamId
                  minimumLatencyMilliseconds: 6.027456183070403
                  encryption:
                    aes128:
                      passcode: passcode
                  port: 6190.222739483032
                  interface: interface
            id: id
            state: ACTIVE
          simpleSettings:
          - value: value
            key: key
          - value: value
            key: key
      properties:
        updateId:
          title: updateId
          type: string
        payload:
          $ref: "#/components/schemas/DeviceConfiguration"
      title: ConfigurationData
      type: object
    ConnectRequestContent:
      example:
        hostId: hostId
        registration:
          channels:
          - profileSetting:
            - name: name
              id: id
              info: info
            - name: name
              id: id
              info: info
            name: name
            channelType: SOURCE
            id: id
            simpleSettings:
            - enums:
                defaultValue: defaultValue
                values:
                - values
                - values
              ranges:
                min: 0.8008281904610115
                max: 6.027456183070403
                defaultValue: 1.4658129805029452
              name: name
              id: id
              info: info
            - enums:
                defaultValue: defaultValue
                values:
                - values
                - values
              ranges:
                min: 0.8008281904610115
                max: 6.027456183070403
                defaultValue: 1.4658129805029452
              name: name
              id: id
              info: info
            connectionProtocols:
            - SRT_LISTENER
            - SRT_LISTENER
          - profileSetting:
            - name: name
              id: id
              info: info
            - name: name
              id: id
              info: info
            name: name
            channelType: SOURCE
            id: id
            simpleSettings:
            - enums:
                defaultValue: defaultValue
                values:
                - values
                - values
              ranges:
                min: 0.8008281904610115
                max: 6.027456183070403
                defaultValue: 1.4658129805029452
              name: name
              id: id
              info: info
            - enums:
                defaultValue: defaultValue
                values:
                - values
                - values
              ranges:
                min: 0.8008281904610115
                max: 6.027456183070403
                defaultValue: 1.4658129805029452
              name: name
              id: id
              info: info
            connectionProtocols:
            - SRT_LISTENER
            - SRT_LISTENER
          simpleSettings:
          - enums:
              defaultValue: defaultValue
              values:
              - values
              - values
            ranges:
              min: 0.8008281904610115
              max: 6.027456183070403
              defaultValue: 1.4658129805029452
            name: name
            id: id
            info: info
          - enums:
              defaultValue: defaultValue
              values:
              - values
              - values
            ranges:
              min: 0.8008281904610115
              max: 6.027456183070403
              defaultValue: 1.4658129805029452
            name: name
            id: id
            info: info
          thumbnails:
          - name: name
            localPath: localPath
            id: id
          - name: name
            localPath: localPath
            id: id
      properties:
        registration:
          $ref: "#/components/schemas/DeviceRegistration"
        hostId:
          title: hostId
          type: string
      required:
      - hostId
      - registration
      title: ConnectRequestContent
      type: object
    ConnectResponseContent:
      example:
        expires: 0.8008281904610115
        success: true
        state: state
        message: message
        error:
          details: details
          type: type
          message: message
        region: region
        deviceId: deviceId
        pairingCode: pairingCode
      properties:
        success:
          title: success
          type: boolean
        state:
          title: state
          type: string
        message:
          title: message
          type: string
        error:
          $ref: "#/components/schemas/ErrorDetails"
        deviceId:
          title: deviceId
          type: string
        region:
          title: region
          type: string
        pairingCode:
          title: pairingCode
          type: string
        expires:
          title: expires
          type: number
      required:
      - message
      - state
      - success
      title: ConnectResponseContent
      type: object
    Connection:
      example:
        transportProtocol:
          srtListener:
            streamId: streamId
            minimumLatencyMilliseconds: 6.027456183070403
            encryption:
              aes128:
                passcode: passcode
            port: 6190.222739483032
            interface: interface
      properties:
        transportProtocol:
          $ref: "#/components/schemas/TransportProtocol"
      title: Connection
      type: object
    DeprovisionResponseContent:
      example:
        success: true
        state: state
        message: message
        error:
          details: details
          type: type
          message: message
      properties:
        success:
          title: success
          type: boolean
        state:
          title: state
          type: string
        message:
          title: message
          type: string
        error:
          $ref: "#/components/schemas/ErrorDetails"
      required:
      - message
      - state
      - success
      title: DeprovisionResponseContent
      type: object
    DeviceConfiguration:
      example:
        channels:
        - settings:
            simpleSettings:
            - value: value
              key: key
            - value: value
              key: key
          connection:
            transportProtocol:
              srtListener:
                streamId: streamId
                minimumLatencyMilliseconds: 6.027456183070403
                encryption:
                  aes128:
                    passcode: passcode
                port: 6190.222739483032
                interface: interface
          id: id
          state: ACTIVE
        - settings:
            simpleSettings:
            - value: value
              key: key
            - value: value
              key: key
          connection:
            transportProtocol:
              srtListener:
                streamId: streamId
                minimumLatencyMilliseconds: 6.027456183070403
                encryption:
                  aes128:
                    passcode: passcode
                port: 6190.222739483032
                interface: interface
          id: id
          state: ACTIVE
        simpleSettings:
        - value: value
          key: key
        - value: value
          key: key
      properties:
        channels:
          items:
            $ref: "#/components/schemas/ChannelConfiguration"
          title: channels
          type: array
        simpleSettings:
          items:
            $ref: "#/components/schemas/IdAndValue"
          title: simpleSettings
          type: array
      required:
      - channels
      title: DeviceConfiguration
      type: object
    DeviceRegistration:
      example:
        channels:
        - profileSetting:
          - name: name
            id: id
            info: info
          - name: name
            id: id
            info: info
          name: name
          channelType: SOURCE
          id: id
          simpleSettings:
          - enums:
              defaultValue: defaultValue
              values:
              - values
              - values
            ranges:
              min: 0.8008281904610115
              max: 6.027456183070403
              defaultValue: 1.4658129805029452
            name: name
            id: id
            info: info
          - enums:
              defaultValue: defaultValue
              values:
              - values
              - values
            ranges:
              min: 0.8008281904610115
              max: 6.027456183070403
              defaultValue: 1.4658129805029452
            name: name
            id: id
            info: info
          connectionProtocols:
          - SRT_LISTENER
          - SRT_LISTENER
        - profileSetting:
          - name: name
            id: id
            info: info
          - name: name
            id: id
            info: info
          name: name
          channelType: SOURCE
          id: id
          simpleSettings:
          - enums:
              defaultValue: defaultValue
              values:
              - values
              - values
            ranges:
              min: 0.8008281904610115
              max: 6.027456183070403
              defaultValue: 1.4658129805029452
            name: name
            id: id
            info: info
          - enums:
              defaultValue: defaultValue
              values:
              - values
              - values
            ranges:
              min: 0.8008281904610115
              max: 6.027456183070403
              defaultValue: 1.4658129805029452
            name: name
            id: id
            info: info
          connectionProtocols:
          - SRT_LISTENER
          - SRT_LISTENER
        simpleSettings:
        - enums:
            defaultValue: defaultValue
            values:
            - values
            - values
          ranges:
            min: 0.8008281904610115
            max: 6.027456183070403
            defaultValue: 1.4658129805029452
          name: name
          id: id
          info: info
        - enums:
            defaultValue: defaultValue
            values:
            - values
            - values
          ranges:
            min: 0.8008281904610115
            max: 6.027456183070403
            defaultValue: 1.4658129805029452
          name: name
          id: id
          info: info
        thumbnails:
        - name: name
          localPath: localPath
          id: id
        - name: name
          localPath: localPath
          id: id
      properties:
        channels:
          items:
            $ref: "#/components/schemas/Channel"
          title: channels
          type: array
        simpleSettings:
          items:
            $ref: "#/components/schemas/Setting"
          title: simpleSettings
          type: array
        thumbnails:
          items:
            $ref: "#/components/schemas/Thumbnail"
          title: thumbnails
          type: array
      required:
      - channels
      title: DeviceRegistration
      type: object
    DeviceStatus:
      example:
        channels:
        - id: id
          state: ACTIVE
          status:
          - name: name
            value: value
            info: info
          - name: name
            value: value
            info: info
        - id: id
          state: ACTIVE
          status:
          - name: name
            value: value
            info: info
          - name: name
            value: value
            info: info
      properties:
        channels:
          items:
            $ref: "#/components/schemas/ChannelStatus"
          title: channels
          type: array
      required:
      - channels
      title: DeviceStatus
      type: object
    DisconnectResponseContent:
      example:
        success: true
        state: state
        message: message
        error:
          details: details
          type: type
          message: message
      properties:
        success:
          title: success
          type: boolean
        state:
          title: state
          type: string
        message:
          title: message
          type: string
        error:
          $ref: "#/components/schemas/ErrorDetails"
      required:
      - message
      - state
      - success
      title: DisconnectResponseContent
      type: object
    Encryption:
      oneOf:
      - $ref: "#/components/schemas/aes128"
      - $ref: "#/components/schemas/aes256"
      title: Encryption
    EncryptionAes128:
      example:
        passcode: passcode
      properties:
        passcode:
          description: A 32-character hexadecimal string.
          maxLength: 32
          minLength: 32
          pattern: "^[a-fA-F0-9]+$"
          title: passcode
          type: string
      required:
      - passcode
      title: EncryptionAes128
      type: object
    EncryptionAes256:
      properties:
        passcode:
          description: A 64-character hexadecimal string.
          maxLength: 64
          minLength: 64
          pattern: "^[a-fA-F0-9]+$"
          title: passcode
          type: string
      required:
      - passcode
      title: EncryptionAes256
      type: object
    EnumValues:
      example:
        defaultValue: defaultValue
        values:
        - values
        - values
      properties:
        values:
          items:
            type: string
          title: values
          type: array
        defaultValue:
          title: defaultValue
          type: string
      required:
      - defaultValue
      - values
      title: EnumValues
      type: object
    ErrorDetails:
      example:
        details: details
        type: type
        message: message
      properties:
        type:
          title: type
          type: string
        message:
          title: message
          type: string
        details:
          title: details
          type: string
      required:
      - details
      - message
      - type
      title: ErrorDetails
      type: object
    GetConfigurationResponseContent:
      example:
        configuration:
          updateId: updateId
          payload:
            channels:
            - settings:
                simpleSettings:
                - value: value
                  key: key
                - value: value
                  key: key
              connection:
                transportProtocol:
                  srtListener:
                    streamId: streamId
                    minimumLatencyMilliseconds: 6.027456183070403
                    encryption:
                      aes128:
                        passcode: passcode
                    port: 6190.222739483032
                    interface: interface
              id: id
              state: ACTIVE
            - settings:
                simpleSettings:
                - value: value
                  key: key
                - value: value
                  key: key
              connection:
                transportProtocol:
                  srtListener:
                    streamId: streamId
                    minimumLatencyMilliseconds: 6.027456183070403
                    encryption:
                      aes128:
                        passcode: passcode
                    port: 6190.222739483032
                    interface: interface
              id: id
              state: ACTIVE
            simpleSettings:
            - value: value
              key: key
            - value: value
              key: key
        success: true
        state: state
        message: message
        error:
          details: details
          type: type
          message: message
      properties:
        success:
          title: success
          type: boolean
        state:
          title: state
          type: string
        message:
          title: message
          type: string
        error:
          $ref: "#/components/schemas/ErrorDetails"
        configuration:
          $ref: "#/components/schemas/ConfigurationData"
      required:
      - message
      - state
      - success
      title: GetConfigurationResponseContent
      type: object
    GetConnectionStatusResponseContent:
      example:
        success: true
        state: state
        message: message
        error:
          details: details
          type: type
          message: message
      properties:
        success:
          title: success
          type: boolean
        state:
          title: state
          type: string
        message:
          title: message
          type: string
        error:
          $ref: "#/components/schemas/ErrorDetails"
      required:
      - message
      - state
      - success
      title: GetConnectionStatusResponseContent
      type: object
    IdAndValue:
      example:
        value: value
        key: key
      properties:
        key:
          title: key
          type: string
        value:
          title: value
          type: string
      title: IdAndValue
      type: object
    Profile:
      example:
        name: name
        id: id
        info: info
      properties:
        name:
          title: name
          type: string
        id:
          title: id
          type: string
        info:
          title: info
          type: string
      required:
      - id
      - info
      - name
      title: Profile
      type: object
    RangeValues:
      example:
        min: 0.8008281904610115
        max: 6.027456183070403
        defaultValue: 1.4658129805029452
      properties:
        min:
          format: double
          title: min
          type: number
        max:
          format: double
          title: max
          type: number
        defaultValue:
          format: double
          title: defaultValue
          type: number
      required:
      - defaultValue
      - max
      - min
      title: RangeValues
      type: object
    ReportActualConfigurationRequestContent:
      example:
        configuration:
          channels:
          - settings:
              simpleSettings:
              - value: value
                key: key
              - value: value
                key: key
            connection:
              transportProtocol:
                srtListener:
                  streamId: streamId
                  minimumLatencyMilliseconds: 6.027456183070403
                  encryption:
                    aes128:
                      passcode: passcode
                  port: 6190.222739483032
                  interface: interface
            id: id
            state: ACTIVE
          - settings:
              simpleSettings:
              - value: value
                key: key
              - value: value
                key: key
            connection:
              transportProtocol:
                srtListener:
                  streamId: streamId
                  minimumLatencyMilliseconds: 6.027456183070403
                  encryption:
                    aes128:
                      passcode: passcode
                  port: 6190.222739483032
                  interface: interface
            id: id
            state: ACTIVE
          simpleSettings:
          - value: value
            key: key
          - value: value
            key: key
      properties:
        configuration:
          $ref: "#/components/schemas/DeviceConfiguration"
      required:
      - configuration
      title: ReportActualConfigurationRequestContent
      type: object
    ReportActualConfigurationResponseContent:
      example:
        success: true
        state: state
        message: message
        error:
          details: details
          type: type
          message: message
      properties:
        success:
          title: success
          type: boolean
        state:
          title: state
          type: string
        message:
          title: message
          type: string
        error:
          $ref: "#/components/schemas/ErrorDetails"
      required:
      - message
      - state
      - success
      title: ReportActualConfigurationResponseContent
      type: object
    ReportStatusRequestContent:
      example:
        status:
          channels:
          - id: id
            state: ACTIVE
            status:
            - name: name
              value: value
              info: info
            - name: name
              value: value
              info: info
          - id: id
            state: ACTIVE
            status:
            - name: name
              value: value
              info: info
            - name: name
              value: value
              info: info
      properties:
        status:
          $ref: "#/components/schemas/DeviceStatus"
      required:
      - status
      title: ReportStatusRequestContent
      type: object
    ReportStatusResponseContent:
      example:
        success: true
        state: state
        message: message
        error:
          details: details
          type: type
          message: message
      properties:
        success:
          title: success
          type: boolean
        state:
          title: state
          type: string
        message:
          title: message
          type: string
        error:
          $ref: "#/components/schemas/ErrorDetails"
      required:
      - message
      - state
      - success
      title: ReportStatusResponseContent
      type: object
    RistCallerTransportProtocol:
      properties:
        streamId:
          $ref: "#/components/schemas/RistStreamIdentifier"
        ip:
          title: ip
          type: string
        port:
          title: port
          type: number
        minimumLatencyMilliseconds:
          default: 3000
          title: minimumLatencyMilliseconds
          type: number
        encryption:
          $ref: "#/components/schemas/Encryption"
      required:
      - ip
      - minimumLatencyMilliseconds
      - port
      title: RistCallerTransportProtocol
      type: object
    RistListenerTransportProtocol:
      properties:
        streamId:
          $ref: "#/components/schemas/RistStreamIdentifier"
        port:
          title: port
          type: number
        minimumLatencyMilliseconds:
          default: 3000
          title: minimumLatencyMilliseconds
          type: number
        encryption:
          $ref: "#/components/schemas/Encryption"
        interface:
          title: interface
          type: string
      required:
      - minimumLatencyMilliseconds
      - port
      title: RistListenerTransportProtocol
      type: object
    RistStreamIdentifier:
      oneOf:
      - $ref: "#/components/schemas/synchronizationSource"
      - $ref: "#/components/schemas/streamId"
      title: RistStreamIdentifier
    Setting:
      example:
        enums:
          defaultValue: defaultValue
          values:
          - values
          - values
        ranges:
          min: 0.8008281904610115
          max: 6.027456183070403
          defaultValue: 1.4658129805029452
        name: name
        id: id
        info: info
      properties:
        id:
          title: id
          type: string
        name:
          title: name
          type: string
        info:
          title: info
          type: string
        enums:
          $ref: "#/components/schemas/EnumValues"
        ranges:
          $ref: "#/components/schemas/RangeValues"
      required:
      - id
      - info
      - name
      title: Setting
      type: object
    SettingProfile:
      properties:
        id:
          title: id
          type: string
      required:
      - id
      title: SettingProfile
      type: object
    SettingsChoice:
      oneOf:
      - $ref: "#/components/schemas/simpleSettings"
      - $ref: "#/components/schemas/profileSetting"
      title: SettingsChoice
    SrtCallerTransportProtocol:
      properties:
        streamId:
          title: streamId
          type: string
        ip:
          title: ip
          type: string
        port:
          maximum: 65535
          minimum: 1
          title: port
          type: number
        minimumLatencyMilliseconds:
          default: 3000
          title: minimumLatencyMilliseconds
          type: number
        encryption:
          $ref: "#/components/schemas/Encryption"
      required:
      - ip
      - minimumLatencyMilliseconds
      - port
      title: SrtCallerTransportProtocol
      type: object
    SrtListenerTransportProtocol:
      example:
        streamId: streamId
        minimumLatencyMilliseconds: 6.027456183070403
        encryption:
          aes128:
            passcode: passcode
        port: 6190.222739483032
        interface: interface
      properties:
        streamId:
          title: streamId
          type: string
        port:
          maximum: 65535
          minimum: 1024
          title: port
          type: number
        minimumLatencyMilliseconds:
          default: 3000
          title: minimumLatencyMilliseconds
          type: number
        encryption:
          $ref: "#/components/schemas/Encryption"
        interface:
          title: interface
          type: string
      required:
      - minimumLatencyMilliseconds
      - port
      title: SrtListenerTransportProtocol
      type: object
    StatusValue:
      example:
        name: name
        value: value
        info: info
      properties:
        name:
          title: name
          type: string
        info:
          title: info
          type: string
        value:
          title: value
          type: string
      required:
      - info
      - name
      - value
      title: StatusValue
      type: object
    SupportedProtocol:
      enum:
      - SRT_LISTENER
      - SRT_CALLER
      - ZIXI_LISTENER
      - ZIXI_CALLER
      - RIST_CALLER
      - RIST_LISTENER
      title: SupportedProtocol
      type: string
    Thumbnail:
      example:
        name: name
        localPath: localPath
        id: id
      properties:
        name:
          title: name
          type: string
        id:
          title: id
          type: string
        localPath:
          title: localPath
          type: string
      required:
      - id
      - localPath
      - name
      title: Thumbnail
      type: object
    TransportProtocol:
      oneOf:
      - $ref: "#/components/schemas/srtListener"
      - $ref: "#/components/schemas/srtCaller"
      - $ref: "#/components/schemas/ristListener"
      - $ref: "#/components/schemas/ristCaller"
      - $ref: "#/components/schemas/zixiListener"
      - $ref: "#/components/schemas/zixiCaller"
      title: TransportProtocol
    ZixiCallerTransportProtocol:
      properties:
        streamId:
          title: streamId
          type: string
        ip:
          title: ip
          type: string
        port:
          title: port
          type: number
        minimumLatencyMilliseconds:
          default: 3000
          title: minimumLatencyMilliseconds
          type: number
        encryption:
          $ref: "#/components/schemas/Encryption"
      required:
      - ip
      - minimumLatencyMilliseconds
      - port
      - streamId
      title: ZixiCallerTransportProtocol
      type: object
    ZixiListenerTransportProtocol:
      properties:
        streamId:
          title: streamId
          type: string
        port:
          title: port
          type: number
        minimumLatencyMilliseconds:
          default: 3000
          title: minimumLatencyMilliseconds
          type: number
        encryption:
          $ref: "#/components/schemas/Encryption"
        interface:
          title: interface
          type: string
      required:
      - minimumLatencyMilliseconds
      - port
      - streamId
      title: ZixiListenerTransportProtocol
      type: object
    aes128:
      example:
        aes128:
          passcode: passcode
      properties:
        aes128:
          $ref: "#/components/schemas/EncryptionAes128"
      required:
      - aes128
      title: aes128
      type: object
    aes256:
      properties:
        aes256:
          $ref: "#/components/schemas/EncryptionAes256"
      required:
      - aes256
      title: aes256
      type: object
    synchronizationSource:
      properties:
        synchronizationSource:
          title: synchronizationSource
          type: number
      required:
      - synchronizationSource
      title: synchronizationSource
      type: object
    streamId:
      properties:
        streamId:
          title: streamId
          type: string
      required:
      - streamId
      title: streamId
      type: object
    simpleSettings:
      example:
        simpleSettings:
        - value: value
          key: key
        - value: value
          key: key
      properties:
        simpleSettings:
          items:
            $ref: "#/components/schemas/IdAndValue"
          title: simpleSettings
          type: array
      required:
      - simpleSettings
      title: simpleSettings
      type: object
    profileSetting:
      properties:
        profileSetting:
          $ref: "#/components/schemas/SettingProfile"
      required:
      - profileSetting
      title: profileSetting
      type: object
    srtListener:
      example:
        srtListener:
          streamId: streamId
          minimumLatencyMilliseconds: 6.027456183070403
          encryption:
            aes128:
              passcode: passcode
          port: 6190.222739483032
          interface: interface
      properties:
        srtListener:
          $ref: "#/components/schemas/SrtListenerTransportProtocol"
      required:
      - srtListener
      title: srtListener
      type: object
    srtCaller:
      properties:
        srtCaller:
          $ref: "#/components/schemas/SrtCallerTransportProtocol"
      required:
      - srtCaller
      title: srtCaller
      type: object
    ristListener:
      properties:
        ristListener:
          $ref: "#/components/schemas/RistListenerTransportProtocol"
      required:
      - ristListener
      title: ristListener
      type: object
    ristCaller:
      properties:
        ristCaller:
          $ref: "#/components/schemas/RistCallerTransportProtocol"
      required:
      - ristCaller
      title: ristCaller
      type: object
    zixiListener:
      properties:
        zixiListener:
          $ref: "#/components/schemas/ZixiListenerTransportProtocol"
      required:
      - zixiListener
      title: zixiListener
      type: object
    zixiCaller:
      properties:
        zixiCaller:
          $ref: "#/components/schemas/ZixiCallerTransportProtocol"
      required:
      - zixiCaller
      title: zixiCaller
      type: object
